<?php

/**
 * This is the model base class for the table "standart_agreements".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StandartAgreements".
 *
 * Columns in table "standart_agreements" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $date
 * @property string $name
 * @property string $filename
 * @property integer $delete
 *
 */
abstract class BaseStandartAgreements extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'standart_agreements';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StandartAgreements|StandartAgreements', $n);
	}

	public static function representingColumn() {
		return 'date';
	}

	public function rules() {
		return array(
            array('agreements', 'file', 'on'=>'update','allowEmpty'=>true),
			array('date, name, filename', 'required'),
			array('delete', 'numerical', 'integerOnly'=>true),
			array('delete', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, date, name, filename, delete', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'date' => Yii::t('app', 'Date'),
			'name' => Yii::t('app', 'Name'),
			'filename' => Yii::t('app', 'Filename'),
			'delete' => Yii::t('app', 'Delete'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('filename', $this->filename, true);
		$criteria->compare('delete', $this->delete);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}