<?php

/**
 * This is the model base class for the table "Gallery".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Gallery".
 *
 * Columns in table "Gallery" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $date_create
 * @property integer $section
 * @property integer $delete
 *
 */
abstract class BaseGallery extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'gallery';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Gallery|Galleries', $n);
	}

	public static function representingColumn() {
		return 'date_create';
	}

	public function rules(){
		return array(
			array('section, delete', 'numerical', 'integerOnly'=>true),
			array('date_create', 'safe'),
			array('date_create, section, delete', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, date_create, section, delete', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'date_create' => Yii::t('app', 'Date Create'),
			'section' => Yii::t('app', 'Section'),
			'delete' => Yii::t('app', 'Delete'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('date_create', $this->date_create, true);
		$criteria->compare('section', $this->section);
		$criteria->compare('delete', $this->delete);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}