<?php

/**
 * This is the model base class for the table "users".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Users".
 *
 * Columns in table "users" available as properties of the model,
 * followed by relations of table "users" available as properties of the model.
 *
 * @property integer $id
 * @property string $login
 * @property string $password
 * @property string $phone
 * @property string $name
 * @property integer $role
 * @property integer $delete
 * @property string $email
 * @property string $generate
 *
 * @property Roles $role0
 */
abstract class BaseUsers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'users';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Users|Users', $n);
	}

	public static function representingColumn() {
		return 'login';
	}

	public function rules() {
		return array(
			array('role, delete', 'numerical', 'integerOnly'=>true),
			array('login', 'length', 'max'=>100),
			array('password, name, generate', 'length', 'max'=>200),
			array('phone', 'length', 'max'=>30),
			array('email', 'length', 'max'=>40),
			array('login, password, phone, name, role, delete, email, generate', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, login, password, phone, name, role, delete, email, generate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'role0' => array(self::BELONGS_TO, 'Roles', 'role'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'login' => Yii::t('app', 'Login'),
			'password' => Yii::t('app', 'Password'),
			'phone' => Yii::t('app', 'Phone'),
			'name' => Yii::t('app', 'Name'),
			'role' => null,
			'delete' => Yii::t('app', 'Delete'),
			'email' => Yii::t('app', 'Email'),
			'generate' => Yii::t('app', 'Generate'),
			'role0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('login', $this->login, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('role', $this->role);
		$criteria->compare('delete', $this->delete);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('generate', $this->generate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}