<?php

/**
 * This is the model base class for the table "clients".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Clients".
 *
 * Columns in table "clients" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $login
 * @property string $password
 * @property string $email
 * @property string $generate
 *
 */
abstract class BaseClients extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'clients';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Clients|Clients', $n);
	}

	public static function representingColumn() {
		return 'login';
	}

	public function rules() {
		return array(
			array('login, password, email', 'required'),
			array('login', 'length', 'max'=>25),
			array('password', 'length', 'max'=>256),
			array('email', 'length', 'max'=>150),
			array('generate', 'length', 'max'=>255),
			array('generate', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, login, password, email, generate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'login' => Yii::t('app', 'Login'),
			'password' => Yii::t('app', 'Password'),
			'email' => Yii::t('app', 'Email'),
			'generate' => Yii::t('app', 'Generate'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('login', $this->login, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('generate', $this->generate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}