<?php

/**
 * This is the model base class for the table "comments".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Comments".
 *
 * Columns in table "comments" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $text
 * @property integer $user_create
 * @property integer $confirm
 * @property integer $delete
 * @property string $date_create
 *
 */
abstract class BaseComments extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'comments';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Comments|Comments', $n);
	}

	public static function representingColumn() {
		return 'text';
	}

	public function rules() {
		return array(
			array('user_create, confirm, delete', 'numerical', 'integerOnly'=>true),
			array('text, date_create', 'safe'),
			array('text, user_create, confirm, delete, date_create', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, text, user_create, confirm, delete, date_create', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'text' => Yii::t('app', 'Text'),
			'user_create' => Yii::t('app', 'User Create'),
			'confirm' => Yii::t('app', 'Confirm'),
			'delete' => Yii::t('app', 'Delete'),
			'date_create' => Yii::t('app', 'Date Create'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('text', $this->text, true);
		$criteria->compare('user_create', $this->user_create);
		$criteria->compare('confirm', $this->confirm);
		$criteria->compare('delete', $this->delete);
		$criteria->compare('date_create', $this->date_create, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}